//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="QTIMetadata.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_metadata_v2p2")]
[System.Xml.Serialization.XmlRootAttribute("qtiMetadata", Namespace="http://www.imsglobal.org/xsd/imsqti_metadata_v2p2", IsNullable=false)]
public partial class QTIMetadataType {
    
    private bool itemTemplateField;
    
    private bool itemTemplateFieldSpecified;
    
    private bool timeDependentField;
    
    private bool timeDependentFieldSpecified;
    
    private bool compositeField;
    
    private bool compositeFieldSpecified;
    
    private QTIMetadataTypeInteractionType[] interactionTypeField;
    
    private QTIMetadataTypeFeedbackType feedbackTypeField;
    
    private bool feedbackTypeFieldSpecified;
    
    private bool solutionAvailableField;
    
    private bool solutionAvailableFieldSpecified;
    
    private QTIMetadataTypeScoringMode[] scoringModeField;
    
    private string toolNameField;
    
    private string toolVersionField;
    
    private string toolVendorField;
    
    /// <remarks/>
    public bool itemTemplate {
        get {
            return this.itemTemplateField;
        }
        set {
            this.itemTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool itemTemplateSpecified {
        get {
            return this.itemTemplateFieldSpecified;
        }
        set {
            this.itemTemplateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool timeDependent {
        get {
            return this.timeDependentField;
        }
        set {
            this.timeDependentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeDependentSpecified {
        get {
            return this.timeDependentFieldSpecified;
        }
        set {
            this.timeDependentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool composite {
        get {
            return this.compositeField;
        }
        set {
            this.compositeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool compositeSpecified {
        get {
            return this.compositeFieldSpecified;
        }
        set {
            this.compositeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("interactionType")]
    public QTIMetadataTypeInteractionType[] interactionType {
        get {
            return this.interactionTypeField;
        }
        set {
            this.interactionTypeField = value;
        }
    }
    
    /// <remarks/>
    public QTIMetadataTypeFeedbackType feedbackType {
        get {
            return this.feedbackTypeField;
        }
        set {
            this.feedbackTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool feedbackTypeSpecified {
        get {
            return this.feedbackTypeFieldSpecified;
        }
        set {
            this.feedbackTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool solutionAvailable {
        get {
            return this.solutionAvailableField;
        }
        set {
            this.solutionAvailableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool solutionAvailableSpecified {
        get {
            return this.solutionAvailableFieldSpecified;
        }
        set {
            this.solutionAvailableFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("scoringMode")]
    public QTIMetadataTypeScoringMode[] scoringMode {
        get {
            return this.scoringModeField;
        }
        set {
            this.scoringModeField = value;
        }
    }
    
    /// <remarks/>
    public string toolName {
        get {
            return this.toolNameField;
        }
        set {
            this.toolNameField = value;
        }
    }
    
    /// <remarks/>
    public string toolVersion {
        get {
            return this.toolVersionField;
        }
        set {
            this.toolVersionField = value;
        }
    }
    
    /// <remarks/>
    public string toolVendor {
        get {
            return this.toolVendorField;
        }
        set {
            this.toolVendorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/imsqti_metadata_v2p2")]
public enum QTIMetadataTypeInteractionType {
    
    /// <remarks/>
    associateInteraction,
    
    /// <remarks/>
    choiceInteraction,
    
    /// <remarks/>
    customInteraction,
    
    /// <remarks/>
    drawingInteraction,
    
    /// <remarks/>
    endAttemptInteraction,
    
    /// <remarks/>
    extendedTextInteraction,
    
    /// <remarks/>
    gapMatchInteraction,
    
    /// <remarks/>
    graphicAssociateInteraction,
    
    /// <remarks/>
    graphicGapMatchInteraction,
    
    /// <remarks/>
    graphicOrderInteraction,
    
    /// <remarks/>
    hotspotInteraction,
    
    /// <remarks/>
    hottextInteraction,
    
    /// <remarks/>
    inlineChoiceInteraction,
    
    /// <remarks/>
    matchInteraction,
    
    /// <remarks/>
    mediaInteraction,
    
    /// <remarks/>
    orderInteraction,
    
    /// <remarks/>
    positionObjectInteraction,
    
    /// <remarks/>
    selectPointInteraction,
    
    /// <remarks/>
    sliderInteraction,
    
    /// <remarks/>
    textEntryInteraction,
    
    /// <remarks/>
    uploadInteraction,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/imsqti_metadata_v2p2")]
public enum QTIMetadataTypeFeedbackType {
    
    /// <remarks/>
    adaptive,
    
    /// <remarks/>
    nonadaptive,
    
    /// <remarks/>
    none,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/imsqti_metadata_v2p2")]
public enum QTIMetadataTypeScoringMode {
    
    /// <remarks/>
    human,
    
    /// <remarks/>
    externalmachine,
    
    /// <remarks/>
    responseprocessing,
}
