//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="UsageData.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
[System.Xml.Serialization.XmlRootAttribute("usageData", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2", IsNullable=false)]
public partial class UsageDataType {
    
    private object[] itemsField;
    
    private string glossaryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("categorizedStatistic", typeof(CategorizedStatisticType))]
    [System.Xml.Serialization.XmlElementAttribute("ordinaryStatistic", typeof(OrdinaryStatisticType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string glossary {
        get {
            return this.glossaryField;
        }
        set {
            this.glossaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="CategorizedStatistic.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
public partial class CategorizedStatisticType {
    
    private TargetObjectType[] targetObjectField;
    
    private MappingType mappingField;
    
    private string nameField;
    
    private string glossaryField;
    
    private string contextField;
    
    private string caseCountField;
    
    private double stdErrorField;
    
    private bool stdErrorFieldSpecified;
    
    private double stdDeviationField;
    
    private bool stdDeviationFieldSpecified;
    
    private System.DateTime lastUpdatedField;
    
    private bool lastUpdatedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("targetObject")]
    public TargetObjectType[] targetObject {
        get {
            return this.targetObjectField;
        }
        set {
            this.targetObjectField = value;
        }
    }
    
    /// <remarks/>
    public MappingType mapping {
        get {
            return this.mappingField;
        }
        set {
            this.mappingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string glossary {
        get {
            return this.glossaryField;
        }
        set {
            this.glossaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string context {
        get {
            return this.contextField;
        }
        set {
            this.contextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string caseCount {
        get {
            return this.caseCountField;
        }
        set {
            this.caseCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double stdError {
        get {
            return this.stdErrorField;
        }
        set {
            this.stdErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stdErrorSpecified {
        get {
            return this.stdErrorFieldSpecified;
        }
        set {
            this.stdErrorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double stdDeviation {
        get {
            return this.stdDeviationField;
        }
        set {
            this.stdDeviationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stdDeviationSpecified {
        get {
            return this.stdDeviationFieldSpecified;
        }
        set {
            this.stdDeviationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime lastUpdated {
        get {
            return this.lastUpdatedField;
        }
        set {
            this.lastUpdatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastUpdatedSpecified {
        get {
            return this.lastUpdatedFieldSpecified;
        }
        set {
            this.lastUpdatedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="TargetObject.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
public partial class TargetObjectType : EmptyPrimitiveTypeType {
    
    private string identifierField;
    
    private string partIdentifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string partIdentifier {
        get {
            return this.partIdentifierField;
        }
        set {
            this.partIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetObjectType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MapEntryType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="EmptyPrimitiveType.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
public partial class EmptyPrimitiveTypeType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Value.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
public partial class ValueType {
    
    private string fieldIdentifierField;
    
    private ValueTypeBaseType baseTypeField;
    
    private bool baseTypeFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string fieldIdentifier {
        get {
            return this.fieldIdentifierField;
        }
        set {
            this.fieldIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ValueTypeBaseType baseType {
        get {
            return this.baseTypeField;
        }
        set {
            this.baseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool baseTypeSpecified {
        get {
            return this.baseTypeFieldSpecified;
        }
        set {
            this.baseTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
public enum ValueTypeBaseType {
    
    /// <remarks/>
    boolean,
    
    /// <remarks/>
    directedPair,
    
    /// <remarks/>
    duration,
    
    /// <remarks/>
    file,
    
    /// <remarks/>
    @float,
    
    /// <remarks/>
    identifier,
    
    /// <remarks/>
    integer,
    
    /// <remarks/>
    pair,
    
    /// <remarks/>
    point,
    
    /// <remarks/>
    @string,
    
    /// <remarks/>
    uri,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Mapping.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
public partial class MappingType {
    
    private MapEntryType[] mapEntryField;
    
    private double lowerBoundField;
    
    private bool lowerBoundFieldSpecified;
    
    private double upperBoundField;
    
    private bool upperBoundFieldSpecified;
    
    private double defaultValueField;
    
    public MappingType() {
        this.defaultValueField = 0D;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mapEntry")]
    public MapEntryType[] mapEntry {
        get {
            return this.mapEntryField;
        }
        set {
            this.mapEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double lowerBound {
        get {
            return this.lowerBoundField;
        }
        set {
            this.lowerBoundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lowerBoundSpecified {
        get {
            return this.lowerBoundFieldSpecified;
        }
        set {
            this.lowerBoundFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double upperBound {
        get {
            return this.upperBoundField;
        }
        set {
            this.upperBoundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool upperBoundSpecified {
        get {
            return this.upperBoundFieldSpecified;
        }
        set {
            this.upperBoundFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double defaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="MapEntry.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
public partial class MapEntryType : EmptyPrimitiveTypeType {
    
    private string mapKeyField;
    
    private double mappedValueField;
    
    private bool caseSensitiveField;
    
    private bool caseSensitiveFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
    public string mapKey {
        get {
            return this.mapKeyField;
        }
        set {
            this.mapKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double mappedValue {
        get {
            return this.mappedValueField;
        }
        set {
            this.mappedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool caseSensitive {
        get {
            return this.caseSensitiveField;
        }
        set {
            this.caseSensitiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool caseSensitiveSpecified {
        get {
            return this.caseSensitiveFieldSpecified;
        }
        set {
            this.caseSensitiveFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="OrdinaryStatistic.Type", Namespace="http://www.imsglobal.org/xsd/imsqti_usagedata_v2p2")]
public partial class OrdinaryStatisticType {
    
    private TargetObjectType[] targetObjectField;
    
    private ValueType valueField;
    
    private string nameField;
    
    private string glossaryField;
    
    private string contextField;
    
    private string caseCountField;
    
    private double stdErrorField;
    
    private bool stdErrorFieldSpecified;
    
    private double stdDeviationField;
    
    private bool stdDeviationFieldSpecified;
    
    private System.DateTime lastUpdatedField;
    
    private bool lastUpdatedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("targetObject")]
    public TargetObjectType[] targetObject {
        get {
            return this.targetObjectField;
        }
        set {
            this.targetObjectField = value;
        }
    }
    
    /// <remarks/>
    public ValueType value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string glossary {
        get {
            return this.glossaryField;
        }
        set {
            this.glossaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string context {
        get {
            return this.contextField;
        }
        set {
            this.contextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string caseCount {
        get {
            return this.caseCountField;
        }
        set {
            this.caseCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double stdError {
        get {
            return this.stdErrorField;
        }
        set {
            this.stdErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stdErrorSpecified {
        get {
            return this.stdErrorFieldSpecified;
        }
        set {
            this.stdErrorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double stdDeviation {
        get {
            return this.stdDeviationField;
        }
        set {
            this.stdDeviationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stdDeviationSpecified {
        get {
            return this.stdDeviationFieldSpecified;
        }
        set {
            this.stdDeviationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime lastUpdated {
        get {
            return this.lastUpdatedField;
        }
        set {
            this.lastUpdatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastUpdatedSpecified {
        get {
            return this.lastUpdatedFieldSpecified;
        }
        set {
            this.lastUpdatedFieldSpecified = value;
        }
    }
}
