/*
 * Computer Adaptive Testing (CAT) Service OpenAPI (YAML) Definition
 *
 * The Computer Adaptive Testing (CAT) Service enables a standard way of implementing adaptive testing using Question and Test Interoperability (QTI). This service has been described using the IMS Model Driven Specification development approach, this being the Platform Specific Model (PSM) of the service.
 *
 * OpenAPI spec version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Ims.Cat.Models
{ 
    /// <summary>
    /// The response code for when the new Section has been created in the CAT Engine and the associated identifier has been returned. 
    /// </summary>
    [DataContract]
    public partial class CreateSectionResponseBodyDType : IEquatable<CreateSectionResponseBodyDType>
    { 
        /// <summary>
        /// Model Primitive Datatype &#x3D; NCName.
        /// </summary>
        /// <value>Model Primitive Datatype &#x3D; NCName.</value>
        [DataMember(Name="sectionIdentifier")]
        public string SectionIdentifier { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateSectionResponseBodyDType {\n");
            sb.Append("  SectionIdentifier: ").Append(SectionIdentifier).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateSectionResponseBodyDType)obj);
        }

        /// <summary>
        /// Returns true if CreateSectionResponseBodyDType instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateSectionResponseBodyDType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateSectionResponseBodyDType other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SectionIdentifier == other.SectionIdentifier ||
                    SectionIdentifier != null &&
                    SectionIdentifier.Equals(other.SectionIdentifier)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SectionIdentifier != null)
                    hashCode = hashCode * 59 + SectionIdentifier.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateSectionResponseBodyDType left, CreateSectionResponseBodyDType right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateSectionResponseBodyDType left, CreateSectionResponseBodyDType right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
